# Alguns comentários sobre Python

** Exemplos ** da [w3schools](https://www.w3schools.com/python/default.asp)




### Nosso primeiro programa

In [1]:
print('Hello, world!')

Hello, world!


### Variáveis não precisam ser declaradas

In [2]:
x = 5
y = "John"
print(x)
print(y)

5
John


### Tipos numéricos
* Inteiro
* Real
* Complexo

In [4]:
w = "Hello!" # string
x = 1        # int
y = 2.8      # float
z = 1j       # complex
print(type(w))
print(type(x))
print(type(y))
print(type(z))
x = 11111111111111111111111111111111111111111
x * x

<class 'str'>
<class 'int'>
<class 'float'>
<class 'complex'>


123456790123456790123456790123456790123454320987654320987654320987654320987654321

### Variáveis de um tipo podem ser convertidas para outro tipo

In [4]:
x = int(1)   # x será 1
y = int(2.8) # y será 2
z = int("3") # z será 3
print(x, y, z)

1 2 3


### Tipo para texto (String)

In [5]:
a = "Hello, World!"
print(a[0])
print(a[1])
print(a[2:5])
print(len(a))
print(a.lower())
print(a.upper())
print(a.replace("H", "J"))
print(a.split(","))
print(str(1))
print(' '.join(['Hola', 'Mundo']))
print('Fábio Fajardo'.replace('á', 'a'))

H
e
llo
13
hello, world!
HELLO, WORLD!
Jello, World!
['Hello', ' World!']
1
Hola Mundo
Fabio Fajardo


### Operadores Matemáticos
* Adição (+)
* Subtração (-)
* Multiplicação (*)
* Divisão (/)
* Módulo (%)
* Exponenciação (**)
* Divisão inteira (//)

Operações seguem order de precedência usual

In [6]:
print(1 + 1)
print(1 - 1)
print(1 * 1)
print(1 / 2)
print(3 % 2)
print(2 ** 2)
print(3 / 2)

2
0
1
0.5
1
4
1.5


### Operadores de Comparação e tipos booleanos
* Igual (==)
* Diferente (!=)
* Maior (>)
* Menor (<)
* Maior ou igual (>=)
* Menor ou igual (<=)

In [7]:
x = 1
y = 2
print(x == y)
print(x != y)
print(x > y)
print(x < y)
print(2*x <= y + 1)
print(x ** 2 >= y / y)

False
True
False
True
True
True


### Operadores lógicos
* conjunção (and)
* disjunção (or)
* negação (not)

In [5]:
x = 1
y = 2
print(x == 1 and y == 2)
print(x == 1 or y == 3)
print(not x == 2)

True
True
True


## Estruturas de dados

Python tem duas estruturas nativas que são **extremamente** úteis: listas e dicionários

### Listas

Conjunto de elementos representados de uma forma sequencial

In [7]:
lista = ["maçã", "banana", "abacate"]
lista[1] = "amora"            # segundo elemento da lista
print(len(lista))             # número de elementos
print(lista)        
lista.append("laranja")       # adiciona no final
print(lista)
lista.sort()                  # ordena
print(lista)
lista[3]

3
['maçã', 'amora', 'abacate']
['maçã', 'amora', 'abacate', 'laranja']
['abacate', 'amora', 'laranja', 'maçã']


'maçã'

### Dicionários

Funciona como uma tabela de associação. Chaves são mapeadas para elementos

In [12]:
dicionario = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(dicionario, "giovanni", sep = ';', end = '=)')

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964};giovanni=)

In [11]:
x = dicionario["model"] # acessando elementos por meio da chave
print(x)

Mustang


In [12]:
dicionario["year"] = 2018
print(dicionario)

{'brand': 'Ford', 'model': 'Mustang', 'year': 2018}


In [13]:
print(dicionario.values()) # Elementos de um dicionário

dict_values(['Ford', 'Mustang', 2018])


In [14]:
print(dicionario.keys()) # Chaves de um dicionário

dict_keys(['brand', 'model', 'year'])


In [15]:
print(dicionario.items()) # pares (chave, elemento) de um dicionário

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 2018)])


In [16]:
print(len(dicionario)) # número de elementos

3


In [17]:
'year' in dicionario # verifica se o dicionário tem a chave 'year'

True

In [18]:
'portas' in dicionario # verifica se o dicionário tem a chave 'portas'

False

In [24]:
dicionario[1] = [2, 3, 4]
dicionario[frozenset((2, 3))] = 1
dicionario[frozenset((2, 3))]

1

### Comandos condicionais

#### Repare o 'tab'. Assim que os blocos de código são definidos

In [19]:
a = 33
b = 200
if b > a:
  print("b é maior que a")

b é maior que a


In [20]:
a = 33
b = 200
if a > b:
  print("b é maior que a a")

In [21]:
a = 33
b = 33
if b > a:
  print("b é maior que a")
elif a == b:
  print("a e b são iguais")

a e b são iguais


In [22]:
a = 200
b = 33
if b > a:
  print("b is greater than a")
elif a == b:
  print("a and b are equal")
else:
  print("a é maior que b")

a é maior que b


### Laço de Repetição (For)

In [23]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

apple
banana
cherry


In [24]:
for x in "banana":
  print(x)

b
a
n
a
n
a


In [25]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x) 
  if x == "banana":
    break

apple
banana


In [26]:
fruits = ["apple", "banana", "cherry"]
for x in fruits:
  if x == "banana":
    continue
  print(x)

apple
cherry


In [27]:
for x in range(6):
  print(x)

0
1
2
3
4
5


In [28]:
for x in range(2, 6):
  print(x)

2
3
4
5


In [29]:
for x in range(2, 30, 3):
  print(x)

2
5
8
11
14
17
20
23
26
29


### Funções

O exemplo a seguir apresenta uma função para calcular o fatorial de um número $n$

In [30]:
def fat(n):
  f = 1
  for i in range(n):
    f = f * (i+1)
  return f

## Vetores e Matrizes

É necessário utlizar a biblioteca **numpy** para lidar com vetores e matrizes de forma eficiente em Python

Em numpy, vetores e matrizes são generalizados por meio do conceito de *arrays* (arranjos)


In [26]:
import numpy as np

### Vetores

In [27]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [28]:
print("Soma = ", np.sum(x))
print("Média = ", np.mean(x))
print("Máximo = ", np.max(x))
print("Mínimo = ", np.min(x))
print("Desvio Padrão = ", np.std(x))
print("Mediana = ", np.median(x))
print("Percentil 90 = ", np.percentile(x, 90))
print("Dimensionalidade = ", x.shape)

Soma =  10
Média =  2.5
Máximo =  4
Mínimo =  1
Desvio Padrão =  1.118033988749895
Mediana =  2.5
Percentil 90 =  3.7
Dimensionalidade =  (4,)


In [29]:
print(x)
print(x + 1)          # somar constante
print(2 * x)          # multiplicar por constante
print(x + x)          # somar vetores
print(x * x)          # multiplicar vetores (elementos)
print(x.dot(x))       # produto escalar
print(np.outer(x, x)) # produto externo

[1 2 3 4]
[2 3 4 5]
[2 4 6 8]
[2 4 6 8]
[ 1  4  9 16]
30
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [30]:
y = np.zeros(5)
z = np.ones(5)
print(y)
print(z)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


### Matrizes

In [31]:
X = np.array([[1,2,3,4],[8,7,6,5],[9,10,11,12]])
print(X)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [32]:
print("Dimensionalidade = ", X.shape)

Dimensionalidade =  (3, 4)


In [33]:
print(np.sum(X))

78


In [35]:
print(np.sum(X, axis = 0))

[18 19 20 21]


In [40]:
print(np.sum(X, axis = 1))

[10 26 42]


In [41]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [42]:
Y = np.zeros((4,3))
Z = np.ones((4,3))
print(Y)
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [43]:
print(X + 1)
print(2 * X)
print(X + X)
print(X * X)
print(X.T)
print(X.dot(X.T))
print(np.matmul(X, X.T))

[[ 2  3  4  5]
 [ 9  8  7  6]
 [10 11 12 13]]
[[ 2  4  6  8]
 [16 14 12 10]
 [18 20 22 24]]
[[ 2  4  6  8]
 [16 14 12 10]
 [18 20 22 24]]
[[  1   4   9  16]
 [ 64  49  36  25]
 [ 81 100 121 144]]
[[ 1  8  9]
 [ 2  7 10]
 [ 3  6 11]
 [ 4  5 12]]
[[ 30  60 110]
 [ 60 174 268]
 [110 268 446]]
[[ 30  60 110]
 [ 60 174 268]
 [110 268 446]]


In [44]:
print(X.dot(np.eye(4)))

[[ 1.  2.  3.  4.]
 [ 8.  7.  6.  5.]
 [ 9. 10. 11. 12.]]


**WARNING** Dada uma matriz $X$, calcular uma nova matriz $Y$ cujos elementos sejam os elementos de $X$ subtraídos das médias de suas respectivas colunas

In [36]:
X = np.array([[1,2,3,4],[8,7,6,5],[9,10,11, 12]])
M = X.mean(axis = 0)
X - M

array([[-5.        , -4.33333333, -3.66666667, -3.        ],
       [ 2.        ,  0.66666667, -0.66666667, -2.        ],
       [ 3.        ,  3.66666667,  4.33333333,  5.        ]])

Numpy permite a indexação de submatrizes

In [46]:
X = np.array([[1,2,3,4],[8,7,6,5],[9,10,11, 12]])
X

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [47]:
# linha zero
X[0]

array([1, 2, 3, 4])

In [48]:
# Elemento da linha 0 e coluna 1
X[0, 1]

2

In [49]:
# Coluna 1
X[:, 1]

array([ 2,  7, 10])

In [50]:
# última coluna
X[:, -1]

array([ 4,  5, 12])

In [51]:
# o que esse faz?
X[-2:, -2:]

array([[ 6,  5],
       [11, 12]])

### Álgebra Linear

Dentro da biblioteca numpy, numpy.linalg possui uma série de funções para álgebra linear. Não cobriremos esse tópico hoje...